language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script: echo "TEST"
deploy:
  provider: pypi
  user: alonefire
  password:
    secure: BPLKjhVDFMMNhBRldD1IMzbxSl0hq+MAH+5JXLIiTxENtItbQOqjcJAmyOxRCS0YahJhWPvoS7PlkvnoyV+aoOh4H57aGixO4MzgT2P10EYJF9h5lydfUV7O9j1NIQQtzrJglYg7y7PzfudnyX2KXYGT+TTf9wrVyEyjO9mUblkMiuFD9WW3cHsm1LGfswQjJn0Ae8r3+Si5LoLGvFRhMQaEh/1suwLD66RhmuVvauFqv6v1cmQdovLsbduYReh0g/mpLP1Y4DQagYrds06r7B+DnAW6U3469/SZ5bWDXTj9ew8228vx3GAN39WXeuS1qAXiV3K2quLS3TJAsl6AaA8lcOv7lGhQkaagrvRzDYIu2tjMtu5OmBJGN7vp0O1g/X8b801XKflSxbwQtjb/gR4VfrUzwUOxuxWapkvJ/rGyDoLLIYUF2sJwVjr51+bZ0igJAJ+Tq2tzjqNK1OaxLl5bgd9e6ZEVlFCpkI+ZDOeIkSZJVBUqoi5eUcB4+jo4K3s58Na9HXBTrEsJrSmQogRFLjxmMmM4pauyBZnQLBW3VMWTcHjC/3kqZ7/TS2gWCTKiq69Y0BqgICVA6lOrBb+qpPJd8pj0ejWK/lYHk1mW7WUMLAEeWNOl+MA1dy6U1SERlkPBBli+GyPFXSl6za/AgVNePdLQ2fVaaI7O8gA=
  on:
    python: 3.6
    tags: true
    branch: master
