language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: echo "TEST"
deploy:
  provider: pypi
  user: alonefire
  password:
    secure: gB3cdDBKGZ1xCOnzbYgGzUvuPbKqkkwGTavOZ0C9V1wDggFFxwulPk3RoC1yiE4rJVnKV5glGePRJvsW3XT8bAw4qbn9FtFX05FlIgLWw+FZmfnrkINAOj27ghEwhabnofNLXT/1HstWps4Gyj8mQ2Yh5e4c5OTrf6HiwPCKSFR4M0QR5F/C7RfKUJ/zwkWI2ff7/5yP1x+ezy5XCcnhOG3PtJQy815rdIorQGX9mAUva77EjTVS/zhQWGXrmmHzX5ZdUU/sW+9kwPYxWPxDJQhNbw9VQt4Vhpnfyc3eHkmAXkhOi3T6aNspIE1PaubPQNvG+2hp+zVMVPnflqUsSKWLipVwFwj9WsC5rfgODywySObred/5ZOoum7eaENrtYtXO4ywZ59zV7vlLOu3/ozLWApzk4u7HdFwDU/R5UkRW6QgYbN8WX8bNIcEZfA870ImHbcHvUNn5R0wIq2maLQzxLhTeaQhWKIiZjkkTn44QL4p7DZL4yJdRqSPiGJLv5zfGDV8ESSlMA7qZb9Ij8Vw00+zYjX8suL8yqMEzVr2kFpdo8FzVh6D3yKRnJMNNYaIF939mHQWPTjjq0CWwkzcPoAciFdSBHagpqEmqf9bM7kykPwF8Q7BXrP0f3eWpbBROGSIcgtDvwjO9X7QT9VhV02H5Wnv/zv6blyK0VDY=
  on:
    python: 3.6
    tags: true
    branch: master
